name: Hello World
author: Vani Rao
description: "Greet someone and log the time"
inputs:
  who_to_greet:
    description: 'Person to greet'
    # required: true
    default: 'World'
outputs:
  time:
    description: 'The time when the greeting was made'
    # value: ${{ steps.greet.outputs.time }}
runs:
  using: "docker"
  image: 'Dockerfile'
  # entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'Linux'