name: External Events
on:
    repository_dispatch:
        types: [build]
jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is a string from the repository_dispatch event"
        